 This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package

permissions:
  id-token: write

on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pixi:
    - name: install pixi
      shell: cmd
      if: matrix.os == 'windows'
      run: iwr -useb https://pixi.sh/install.ps1 | iex

    - name: install pixi unix
      shell: bash
      if: matrix.os == 'ubuntu' || matrix.os == 'macos'
      run: curl -fsSL https://pixi.sh/install.sh | bash

    - name: Install Rattler-Build
      shell: bash
      run: |
        pixi global install rattler-build
